# Generated by Django 4.0.6 on 2022-08-21 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatabaseBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Blog_Category', models.CharField(default='Category', max_length=50)),
                ('Blog_Title', models.CharField(default='Enter the Title of Blog', max_length=30)),
                ('Blog_Date', models.DateTimeField(auto_now_add=True)),
                ('Blog_Moral', models.CharField(default='Enter the Moral Of the Blog', max_length=50)),
                ('Blog_Details', models.CharField(default='Write Complete Blog Here', max_length=5000)),
                ('Blog_Author', models.CharField(default='Name Of Blogger', max_length=20)),
            ],
        ),
    ]
