# Generated by Django 4.0.6 on 2022-08-21 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='databaseblog',
            name='Blog_Category',
        ),
    ]
