# Generated by Django 4.0.6 on 2022-08-21 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_databaseblog_blog_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='databaseblog',
            old_name='Blog_Author',
            new_name='BlogAuthor',
        ),
        migrations.RenameField(
            model_name='databaseblog',
            old_name='Blog_Date',
            new_name='BlogDate',
        ),
        migrations.RenameField(
            model_name='databaseblog',
            old_name='Blog_Details',
            new_name='BlogDetails',
        ),
        migrations.RenameField(
            model_name='databaseblog',
            old_name='Blog_Moral',
            new_name='BlogMoral',
        ),
        migrations.RenameField(
            model_name='databaseblog',
            old_name='Blog_Title',
            new_name='BlogTitle',
        ),
    ]
