# Generated by Django 4.0.6 on 2022-08-21 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_databaseblog_blogimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublishBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Author_Name', models.CharField(max_length=50)),
                ('Blogger_Email', models.CharField(max_length=50)),
                ('Blogger_Title', models.CharField(max_length=80)),
                ('Blogger_Content', models.CharField(max_length=5000000)),
            ],
        ),
    ]
