# Generated by Django 4.0.6 on 2022-08-22 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_publishblog_blog_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='publishblog',
            name='Blog_Date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
