# Generated by Django 4.1 on 2022-08-29 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_comments_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='Reply_id',
            field=models.CharField(default='', max_length=500),
        ),
    ]
