# Generated by Django 4.1 on 2022-08-30 09:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0012_alter_comments_reply_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='databaseblog',
            name='BlogImage',
            field=models.ImageField(default=' ', upload_to='shop/image'),
        ),
        migrations.CreateModel(
            name='Publish_Comments',
            fields=[
                ('Sno', models.AutoField(primary_key=True, serialize=False)),
                ('Product_Id', models.CharField(max_length=1000)),
                ('Reply_id', models.IntegerField()),
                ('Comment', models.TextField(max_length=500)),
                ('Commment_Date', models.DateTimeField(auto_now=True)),
                ('Parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.publish_comments')),
                ('Post_Comment_On_User_Blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.publishblog')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
