# Generated by Django 4.1 on 2022-08-30 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_alter_databaseblog_blogimage_publish_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='databaseblog',
            name='BlogTitle',
            field=models.CharField(default='Title', max_length=30),
        ),
    ]
