# Generated by Django 4.1 on 2022-08-30 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_alter_databaseblog_blogtitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='databaseblog',
            name='BlogMoral',
            field=models.CharField(default='Moral Of the Blog', max_length=50),
        ),
    ]
