# Generated by Django 4.1 on 2022-08-30 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_alter_databaseblog_blogmoral'),
    ]

    operations = [
        migrations.AlterField(
            model_name='databaseblog',
            name='BlogDetails',
            field=models.CharField(default='Write Complete Blog', max_length=5000),
        ),
    ]
