# Generated by Django 4.1 on 2022-09-04 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_alter_databaseblog_blogdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publishblog',
            name='Blog_Image',
            field=models.ImageField(default='', upload_to='shop/image/'),
        ),
    ]
