# Generated by Django 4.1 on 2022-09-06 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_alter_publishblog_blog_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publishblog',
            name='Blog_Image',
            field=models.ImageField(upload_to='shop/image/'),
        ),
    ]
