# Generated by Django 4.0.6 on 2022-08-05 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_rename_discription_items_desc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='image',
            field=models.ImageField(default='', upload_to='shop/image'),
        ),
        migrations.AlterField(
            model_name='items',
            name='product_name',
            field=models.CharField(default='Enter Your Name', max_length=50),
        ),
    ]
