# Generated by Django 4.0.6 on 2022-08-13 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_items_image_alter_items_product_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='Name', max_length=50)),
                ('Email', models.CharField(default='Email', max_length=50)),
                ('Phone', models.IntegerField(default='Phone Number', max_length=10)),
                ('desc', models.CharField(default='Enter Your Khawaish', max_length=300)),
                ('pub_date', models.DateField()),
            ],
        ),
    ]
