# Generated by Django 4.0.6 on 2022-08-17 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_remove_contacts_pub_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='Name', max_length=50)),
                ('Email', models.CharField(default='Email', max_length=50)),
                ('Address', models.CharField(default='Address', max_length=50)),
                ('OptionalAdd', models.CharField(default='Optional Address', max_length=50)),
                ('City', models.CharField(default='City', max_length=50)),
                ('State', models.CharField(default='State', max_length=50)),
                ('Pincode', models.CharField(default='Pincode', max_length=50)),
                ('Phone', models.IntegerField(default='Phone Number', max_length=10)),
            ],
        ),
    ]
