# Generated by Django 4.0.6 on 2022-08-17 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_checkout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='OptionalAdd',
        ),
        migrations.AddField(
            model_name='checkout',
            name='Product',
            field=models.CharField(default='Product Names', max_length=100),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='Phone',
            field=models.IntegerField(default='Phone Number'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='Phone',
            field=models.IntegerField(default='Phone Number'),
        ),
    ]
