# Generated by Django 4.0.6 on 2022-08-18 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_rename_porductorderid_checkout_orderid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OrderId', models.CharField(default='Order Id', max_length=100)),
                ('CustomerEnteredOrderId', models.CharField(default='Customer Order Id', max_length=100)),
                ('Description', models.CharField(default='Enter Aboout Product', max_length=500)),
                ('Time', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='checkout',
            name='Product',
            field=models.CharField(default='product name', max_length=1000),
        ),
    ]
