# Generated by Django 4.0.6 on 2022-08-18 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_remove_tracker_customerenteredorderid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tracker',
            old_name='Time',
            new_name='Date',
        ),
    ]
