# Generated by Django 4.0.6 on 2022-08-18 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_rename_time_tracker_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracker',
            name='Date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
