# Generated by Django 4.1 on 2022-09-03 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_alter_checkout_pincode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='Phone',
            field=models.CharField(max_length=11),
        ),
    ]
