# Generated by Django 4.1 on 2022-09-03 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_alter_checkout_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='Phone',
            field=models.CharField(default='Phone Number', max_length=11),
        ),
    ]
